version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fitec_network

  mysql_db:
    image: mysql:8
    container_name: my-mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - fitec_network

  mongo_db:
    image: mongo:latest
    container_name: my-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongodbdata:/data/db
    networks:
      - fitec_network

volumes:
  pgdata:
  mysqldata:
  mongodbdata:

networks:
  fitec_network:
